# Kubernetes Deployment for book_catalog microservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: $CONTAINER_REGISTRY/book-catalog:$VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://week99_user:Nzi8z75PVxThIylXeaotbHEgXIwUeRL0@dpg-cru0galds78s73fchmd0-a.oregon-postgres.render.com/week99
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
# Kubernetes Deployment for inventory_management microservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: $CONTAINER_REGISTRY/inventory-management:$VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://week99_user:Nzi8z75PVxThIylXeaotbHEgXIwUeRL0@dpg-cru0galds78s73fchmd0-a.oregon-postgres.render.com/week99
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
