name: Cloud Native Project
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: "Terraform Validate"
        working-directory: ./terraform
        run: terraform validate

      - name: "Terraform Plan"
        working-directory: ./terraform
        id: plan
        run: terraform plan -out=tfplan

      - name: "Terraform Apply"
        working-directory: ./terraform
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - uses: azure/aks-set-context@v3
        with:
          resource-group: "sit722week99"
          cluster-name: "sit722week99"

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_UN }}
          password: ${{ secrets.REGISTRY_PW }}

      - name: Build
        run: |
          ./scripts/build-image.sh

      - name: Push
        run: |
          ./scripts/push-image.sh

      - name: Deploy to Kubernetes
        run: |
          ./scripts/deploy.sh
